# Generated by Django 6.0.3 on 2026-05-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='return_image',
            field=models.ImageField(blank=True, null=True, upload_to='return_images/'),
        ),
    ]
